import {
  Activity,
  ArrowRight,
  Bell,
  Building2,
  Calendar,
  Camera,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  Download,
  Eye,
  EyeOff,
  FileText,
  Filter,
  GraduationCap,
  Home,
  LayoutGrid,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Moon,
  Phone,
  Plus,
  Search,
  Settings,
  Shield,
  ShieldCheck,
  Sun,
  User,
  Users,
  X,
} from 'lucide-react';

/** Icons shared across all roles / features. */
export const COMMON = {
  LOADER: Loader2,
  PLUS: Plus,
  CHECK: Check,
  COPY: Copy,
  EYE: Eye,
  EYE_OFF: EyeOff,
  SEARCH: Search,
  FILTER: Filter,
  EXPORT: Download,
  LIST_VIEW: List,
  GRID_VIEW: LayoutGrid,
  MAIL: Mail,
  PHONE: Phone,
  LOCK: Lock,
  SHIELD: Shield,
  SHIELD_CHECK: ShieldCheck,
  CHEVRON_DOWN: ChevronDown,
  CHEVRON_RIGHT: ChevronRight,
  CHEVRON_UP: ChevronUp,
  X: X,
  ARROW_RIGHT: ArrowRight,
  GRADUATION_CAP: GraduationCap,
  BUILDING: Building2,
  USERS_GROUP: Users,
  MOON: Moon,
  SUN: Sun,
  USER: User,
  HOME: Home,
  BELL: Bell,
  MENU: Menu,
  ACTIVITY: Activity,
  CALENDAR: Calendar,
  CAMERA: Camera,
  CLOCK: Clock,
  FILE_TEXT: FileText,
  LOGOUT: LogOut,
  SETTINGS: Settings,
};
export default COMMON;
