import {
  Activity,
  ArrowLeft,
  ArrowRight,
  Bell,
  Building2,
  Calendar,
  Camera,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronRight,
  ChevronUp,
  Clock,
  Copy,
  Download,
  Eye,
  EyeOff,
  FileQuestion,
  FileText,
  Filter,
  GraduationCap,
  Home,
  Info,
  LayoutGrid,
  LifeBuoy,
  List,
  Loader2,
  Lock,
  LogOut,
  Mail,
  Menu,
  Moon,
  Phone,
  Plus,
  Power,
  RotateCcw,
  Search,
  ServerCrash,
  Settings,
  Shield,
  ShieldAlert,
  ShieldCheck,
  Sun,
  Trash2,
  User,
  Users,
  Wrench,
  X,
} from 'lucide-react';

/** Icons shared across all roles / features. */
export const COMMON = {
  ACTIVITY: Activity,
  ARROW_LEFT: ArrowLeft,
  ARROW_RIGHT: ArrowRight,
  BELL: Bell,
  BUILDING: Building2,
  CALENDAR: Calendar,
  CAMERA: Camera,
  CHECK: Check,
  CHECK_CIRCLE: CheckCircle,
  CHEVRON_DOWN: ChevronDown,
  CHEVRON_RIGHT: ChevronRight,
  CHEVRON_UP: ChevronUp,
  CLOCK: Clock,
  COPY: Copy,
  EXPORT: Download,
  EYE: Eye,
  EYE_OFF: EyeOff,
  FILE_QUESTION: FileQuestion,
  FILE_TEXT: FileText,
  FILTER: Filter,
  GRADUATION_CAP: GraduationCap,
  GRID_VIEW: LayoutGrid,
  HOME: Home,
  INFO: Info,
  LIFE_BUOY: LifeBuoy,
  LIST_VIEW: List,
  LOADER: Loader2,
  LOCK: Lock,
  LOGOUT: LogOut,
  MAIL: Mail,
  MENU: Menu,
  MOON: Moon,
  PHONE: Phone,
  PLUS: Plus,
  POWER: Power,
  ROTATE_CCW: RotateCcw,
  SEARCH: Search,
  SERVER_CRASH: ServerCrash,
  SETTINGS: Settings,
  SHIELD: Shield,
  SHIELD_ALERT: ShieldAlert,
  SHIELD_CHECK: ShieldCheck,
  SUN: Sun,
  TRASH: Trash2,
  USER: User,
  USERS_GROUP: Users,
  WRENCH: Wrench,
  X: X,
};
export default COMMON;
